name: "CodeQL, black, flake8 checks"

on:
  push:
    # Run on all branches
    branches:
      - '**'
    # Run on any file change
    paths:
      - '**/*.py'
  pull_request:
    # Run on all branches
    branches:
      - '**'
    # Run on any file change
    paths:
      - '**/*.py'

jobs:
  analyse:
    name: Analyze using GitHub CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Perform black lint check
      uses: psf/black@stable

    - name: Perform flake8 lint check
      uses: py-actions/flake8@v2
